# Generated by Django 3.2.7 on 2021-09-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volum_weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
